# Authenticated Received Chain (ARC) Signing
allow_username_mismatch = true;
sign_authenticated = true;
use_domain = "envelope";
default_selector = "mail";
path = "/var/lib/rspamd/dkim/$domain.$selector.key";
