# Authenticated Received Chain (ARC) Signing
allow_username_mismatch = true;
allow_hdrfrom_mismatch = true;
allow_hdrfrom_multiple = true;
sign_authenticated = true;
sign_local = true;
sign_inbound = true;
auth_only = false;
sign_networks = [ "127.0.0.0/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16" ];
use_esld = false;
use_domain = "header";
default_selector = "mail";
path = "/var/lib/rspamd/dkim/$domain.$selector.key";
